"use strict";
let isTrue = true;
let age = 30;
let fullName = "Liton";
fullName = "Mamun";
let lastName = "Al-Mamun";
lastName = 198;
const names = [];
names.push("Liton");
const aj = ["liton", "mamun"];
let myTuple;
myTuple = [4, true, "Liton Vaiya"];
console.log(myTuple);
